### ISSUE TITLE
How to use this pod with Swift?

### ISSUE THREAD

**Issue by dragonikpl** [clemensg/sqlite3pod#10]
I was trying to use this pod inside Swift code, but I cannot import the correct sqlite, as Apple provides it's own sqlite when doing `import Sqlite3`.

**Comment by clemensg** [comment]
Hi,

I think you have to create a bridging header, as documented in https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift

There you should then have a `#include <sqlite3/sqlite3.h>` statement.

With this, all C functions from the sqlite header file should then appear as "Swift global functions" according to https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/using_imported_c_functions_in_swift

Let me know if it works.
