### ISSUE TITLE
Specify specific SQLite version?

### ISSUE THREAD

**Issue by gennaios** [clemensg/sqlite3pod#11]
Hello,

It seems such hasn't been asked before and perhaps as such, I am unsure about interest and likelihood of such being possible or added. Is there a way to specify and pin a specific SQLite version, or version greater than/equal, etc.? It seems such can't be done at the moment; might you someday consider it? For testing purposes, I believe such can be downloaded and there is a specific format for the archive URL, using specific branches such as trunk would be nice too.

**Comment by clemensg** [comment]
Hi,

specifying/locking versions is already possible in CocoaPods: https://guides.cocoapods.org/using/the-podfile.html
For example, to stay on 3.30.0, you just have to specify `pod 'sqlite3', '3.30.0'` in your Podfile.

**Comment by gennaios** [comment]
Thank you. Ah yes, I forgot to think specific versions of this Pod would be for SQLite versions as well. Question was more so concerning the ability to use and test trunk and other branches.

**Comment by clemensg** [comment]
What you can always do is, make your own podspec file based on sqlite3.podspec and in your Podfile, reference it via the podspec argument, e.g. `pod 'sqlite3', podspec: '~/foo/mysqlite3pod'`. Then you can just modify it, e.g. `s.source = { git: '...', branch: '...' }` in your sqlite3.podspec.

**Comment by gennaios** [comment]
Good idea, thank you. Perhaps such may make it into this pod itself though unsure if any others would use it. who knows.
