### ISSUE TITLE
Publish Git Tags

### ISSUE THREAD

**Issue by vanniktech** [clemensg/sqlite3pod#12]
I'm having a legal requirement where I need to provide links to LICENSES such as https://github.com/clemensg/sqlite3pod/blob/master/LICENSE with the version I'm using. In my case 3.33.0. Providing a link from the master branch isn't enough.

This is one of the 2 libraries I'm using that don't publish git tags. Is it possible to publish git tags?

**Comment by clemensg** [comment]
FYI: 3.35.1 is coming soon..

**Comment by vanniktech** [comment]
@clemensg thanks. Would it also be possible to push the old tags for the following versions:

- 3.33.0
- 3.34.0

Thanks!

**Comment by clemensg** [comment]
Hi, I'd rather not retroactively push them. Maybe you can upgrade to the latest version 3.35.1 ?

**Comment by vanniktech** [comment]
Long term, yes. For now, I'm stuck on 3.33.0.

```
git checkout b31d3032f58b8c5f479269d560d55a811b2cd194
git tag 3.33.0
git push origin 3.33.0
```

---

```
git checkout dd57a96c2382c0c732a2530e56049d34d98d1fe8
git tag 3.34.0
git push origin 3.34.0
```

---

```
git checkout 590f438d6d781333aa6f45798234801f5e2bfb47
git tag 3.34.1
git push origin 3.34.1
```

Those are the commands you'd need to execute.

**Comment by clemensg** [comment]
Yeah I know how, I just did not want to do unnecessary work, but as you insist, I'll push them.

**Comment by vanniktech** [comment]
@clemensg highly appreciated - thanks!
