### ISSUE TITLE
Using loadable extensions not part of the default amalgation

### ISSUE THREAD

**Issue by simolus3** [clemensg/sqlite3pod#18]
Thanks for this useful pod! I'm currently looking for ways to statically link sqlite3 extensions that are part of the official sources, but not part of the default amalgation. This includes things like user authentication, the expert system or spellfix. 

Do you think there could be a way to expose these as well? I'm not too familiar with CocoaPods, but what I think might work is

1. Include `sqlite3ext.h` in the public headers of the default pod.
2. Adding a second pod (say `sqlite3ext`) which has the complete preprocessed C sources (https://www.sqlite.org/2022/sqlite-preprocessed-3390200.zip) as its source and could define subspecs to build certain extensions.

I'm happy to open a PR for this, I just wanted to ask if you think these additions could belong in this repository.

**Comment by clemensg** [comment]
Hi, maybe we could also use the preprocessed C sources for this pod in general and add subspecs for the extensions that add the additionally needed source_files and CFLAGS?

**Comment by simolus3** [comment]
Good point! Since macOS comes with TCL installed, I think we can also just use the regular sources and run `./configure && make sqlite3.c` as a preprocess step in CocoaPods. Then we have all the other extensions and the amalgamation available for the existing subspecs.

**Comment by clemensg** [comment]
👍 Feel free to open a PR

**Comment by clemensg** [comment]
Hmm, I just have a test project with a Podfile containing e.g. `pod 'sqlite3', inhibit_warnings: true, subspecs: ['fts5'], podspec: '~/Dev/sqlite3pod'`
You mean `source` in `Pod::Spec` ?

**Comment by simolus3** [comment]
Ah yes that works, thank you! I have been using `pod 'sqlite3', :path => '...'` before which didn't work.

I managed to get it working with your advice and I'll open a PR soon.
