### ISSUE TITLE
How do I know my sqlite method calling the pod sqlite.c/sqlite.h instead of iOS's framework

### ISSUE THREAD

**Issue by LawrenceHan** [clemensg/sqlite3pod#5]
@clemensg Sorry for asking a dumb question.

**Comment by clemensg** [comment]
Hi, as the pod has a much newer version of SQLite you can call `sqlite3_libversion` (see https://www.sqlite.org/c3ref/libversion.html) and check if it returns 3.14.2 instead of the certainly older SQLite library version shipped with iOS.

**Comment by LawrenceHan** [comment]
@clemensg Thank you for your kind reply :D
